apiVersion: v1
kind: Service
metadata:
  name: minecraft
  namespace: minecraft
  labels:
    app: minecraft
    tailscale.com/proxy-class: "tailscale-proxy"
  annotations: {}
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
    - name: minecraft
      port: 25565
      targetPort: minecraft
      nodePort: 30001
      protocol: TCP
  selector:
    app: minecraft
