apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: memos-pvc
  namespace: memos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
