apiVersion: v1
kind: Service
metadata:
  name: memos
  namespace: memos
  labels:
    tailscale.com/proxy-class: "tailscale-proxy"
    tailscale.com/hostname: "memos"
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
    - port: 80
      targetPort: 5230
      protocol: TCP
  selector:
    app: memos
