apiVersion: v1
kind: Service
metadata:
  name: memos-service
  namespace: memos
spec:
  type: NodePort
  ports:
    - port: 5230
      targetPort: 5230
      nodePort: 30000
      protocol: TCP
  selector:
    app: memos
