apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: tailscale-proxy
spec:
  statefulSet:
    pod:
      tailscaleContainer:
        resources:
          limits:
            squat.ai/tun: "1"
