apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: prometheus
  labels:
    tailscale.com/proxy-class: "tailscale-proxy"
    tailscale.com/hostname: "grafana"
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: grafana

