apiVersion: v1
kind: Service
metadata:
  name: homeassistant-service
  namespace: homeassistant
  labels:
    tailscale.com/proxy-class: "tailscale-proxy"
    tailscale.com/hostname: "homeassistant"
spec:
  selector:
    app: homeassistant-label
  ports:
  - name: homeassistant
    port: 80
    targetPort: 8123
