apiVersion: apps/v1
kind: Deployment
metadata:
  name: debian
  namespace: debian
  labels:
    app: debian
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debian
  template:
    metadata:
      labels:
        app: debian
    spec:
      containers:
        - name: debian-container
          image: debian:latest
          command: ["sleep"]
          args: ["infinity"]
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: debian
