apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: debian
  namespace: debian
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
