apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma
  namespace: apps
  labels:
    tailscale.com/proxy-class: "tailscale-proxy"
    tailscale.com/hostname: "uptime-kuma"
    helm.sh/chart: uptime-kuma-1.3.6
    app.kubernetes.io/name: uptime-kuma
    app.kubernetes.io/instance: test-uptime
    app.kubernetes.io/version: "1.23.13"
    app.kubernetes.io/managed-by: Helm
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: uptime-kuma
    app.kubernetes.io/instance: test-uptime
