apiVersion: v1
kind: Service
metadata:
  name: memos-service
  namespace: memos
  labels:
    tailscale.com/proxy-class: "tailscale-proxy"
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
    - port: 443
      targetPort: 5230
      protocol: TCP
  selector:
    app: memos
