apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-uptime-uptime-kuma
  namespace: uptime-kuma
  labels:
    helm.sh/chart: uptime-kuma-1.3.6
    app.kubernetes.io/name: uptime-kuma
    app.kubernetes.io/instance: test-uptime
    app.kubernetes.io/version: "1.23.13"
    app.kubernetes.io/managed-by: Helm
