apiVersion: v1
kind: Pod
metadata:
  name: weather
  labels:
    app: weather
spec:
  containers:
    - name: weather
      image: tecke/weather:latest
      env:
        - name: OPEN_WEATHER_API_KEY
          valueFrom:
            secretKeyRef:
              name: weather-config
              key: open_weather_api_key
        - name: LONGITUDE
          valueFrom:
            secretKeyRef:
              name: weather-config
              key: longitude
        - name: LATITUDE
          valueFrom:
            secretKeyRef:
              name: weather-config
              key: latitude
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: weather
spec:
  selector:
    app: weather
  ports:
    - port: 80
      targetPort: 8080

