---
# Source: minecraft/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: "minecraft-minecraft-rcon"
  labels:
    app: minecraft-minecraft
    chart: "minecraft-4.15.0"
    release: "minecraft"
    heritage: "Helm"
    app.kubernetes.io/name: "minecraft"
    app.kubernetes.io/instance: minecraft-minecraft
    app.kubernetes.io/version: "4.15.0"
type: Opaque
data:
  rcon-password: "Q0hBTkdFTUUh"
---
# Source: minecraft/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: "minecraft-minecraft-curseforge"
  labels:
    app: minecraft-minecraft
    chart: "minecraft-4.15.0"
    release: "minecraft"
    heritage: "Helm"
    app.kubernetes.io/name: "minecraft"
    app.kubernetes.io/instance: minecraft-minecraft
    app.kubernetes.io/version: "4.15.0"
type: Opaque
data:
  cf-api-key: "Q0hBTkdFTUUh"
---
# Source: minecraft/templates/minecraft-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: minecraft-minecraft
  labels:
    app: minecraft-minecraft
    chart: "minecraft-4.15.0"
    release: "minecraft"
    heritage: "Helm"
    app.kubernetes.io/name: "minecraft"
    app.kubernetes.io/instance: minecraft-minecraft
    app.kubernetes.io/version: "4.15.0"
  annotations: {}
spec:
  type: ClusterIP
  ports:
    - name: minecraft
      port: 25565
      targetPort: minecraft
      protocol: TCP
  selector:
    app: minecraft-minecraft
---
# Source: minecraft/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-minecraft
  labels:
    app: minecraft-minecraft
    chart: "minecraft-4.15.0"
    release: "minecraft"
    heritage: "Helm"
    app.kubernetes.io/name: "minecraft"
    app.kubernetes.io/instance: minecraft-minecraft
    app.kubernetes.io/version: "4.15.0"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: minecraft-minecraft
  template:
    metadata:
      labels:
        app: minecraft-minecraft
        app.kubernetes.io/name: "minecraft"
        app.kubernetes.io/instance: minecraft-minecraft
        app.kubernetes.io/version: "4.15.0"
    spec:
      securityContext:
        fsGroup: 2000
        runAsGroup: 3000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: minecraft-minecraft
          image: "itzg/minecraft-server:latest"
          imagePullPolicy: IfNotPresent
          tty: true
          stdin: true
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            exec:
              command:
                - mc-health
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 20
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            exec:
              command:
                - mc-health
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 20
            successThreshold: 1
            timeoutSeconds: 1
          env:
            - name: EULA
              value: "true"
            - name: TYPE
              value: "VANILLA"
            - name: VERSION
              value: "LATEST"
            - name: DIFFICULTY
              value: "easy"
            - name: MAX_PLAYERS
              value: "20"
            - name: MAX_WORLD_SIZE
              value: "10000"
            - name: MAX_BUILD_HEIGHT
              value: "256"
            - name: MAX_TICK_TIME
              value: "60000"
            - name: SPAWN_PROTECTION
              value: "16"
            - name: VIEW_DISTANCE
              value: "10"
            - name: MODE
              value: "survival"
            - name: MOTD
              value: "Welcome to Minecraft on Kubernetes!"
            - name: LEVEL_TYPE
              value: "DEFAULT"
            - name: LEVEL
              value: "world"
            - name: MODRINTH_ALLOWED_VERSION_TYPE
              value: "release"
            - name: MEMORY
              value: "1024M"
            - name: OVERRIDE_SERVER_PROPERTIES
              value: "false"
            - name: ENABLE_RCON
              value: "false"

          ports:
            - name: minecraft
              containerPort: 25565
              protocol: TCP
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: datadir
              mountPath: /data
            - name: backupdir
              mountPath: /backups
              readOnly: true
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      volumes:
        - name: tmp
          emptyDir: {}
        - name: datadir
          emptyDir: {}
        - name: backupdir
          emptyDir: {}
