name: Build and Push Frontend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: tecke
        password: ${{ secrets.DOCKERHUB_PAT }}
        
    - name: Build and push Docker images
      run: |
        cd ./services/frontend
        docker build -t tecke/homecluster-frontend -t homecluster-frontend . 
        docker push tecke/homecluster-frontend


